algo_params:
  ent_coef: 0.01
  gamma: 0.99
  learning_rate: 0.001
  n_steps: 16
  vf_coef: 0.5
algorithm: a2c
checkpoint_freq: 0
env_id: Hopper-v5
eval_freq: 0
policy: MlpPolicy
seed: 0
total_timesteps: 1000000
verbose: 0
