algo_params:
  batch_size: 256
  clip_range: 0.2
  ent_coef: 0.01
  gamma: 0.99
  learning_rate: 0.0003
  n_epochs: 10
  n_steps: 2048
algorithm: ppo
checkpoint_freq: 0
env_id: HalfCheetah-v5
eval_freq: 0
policy: MlpPolicy
seed: 4
total_timesteps: 1000000
verbose: 0
