algorithm: sac
env_id: HalfCheetah-v5
seed: 0
total_timesteps: 1000000
policy: MlpPolicy
verbose: 0
checkpoint_freq: 0
eval_freq: 0
algo_params:
  learning_rate: 0.001
  batch_size: 64
  buffer_size: 1000000
  learning_starts: 10000
  gamma: 0.99
  tau: 0.005
  train_freq: 1
  gradient_steps: 1
  ent_coef: auto
  target_update_interval: 1
  use_sde: false
  use_sde_at_warmup: false
