algo_params:
  batch_size: 256
  gamma: 0.99
  learning_rate: 0.0003
  policy_delay: 2
  target_policy_noise: 0.2
  tau: 0.005
algorithm: td3
checkpoint_freq: 0
env_id: HalfCheetah-v5
eval_freq: 0
policy: MlpPolicy
seed: 3
total_timesteps: 1000000
verbose: 0
